### ISSUE TITLE
GPU核显驱动

### ISSUE THREAD

**Issue by PPPOP112** [DHDAXCW/NanoPi-R4S-R4SE#201]
Openwrt 已经适配支持了R4S的T860核显驱动，可否加在新的固件里？

**Comment by DHDAXCW** [comment]
本来想着要开的，结果夏天快到，考虑到散热问题，不知道会怎么样。过几天再试试开着看看

**Comment by zcfan** [comment]
感谢作者，请问这里现在进展如何～
