### ISSUE TITLE
N2N_v3版本

### ISSUE THREAD

**Issue by cnJJHC** [DHDAXCW/NanoPi-R4S-R4SE#204]
N2N_v3版本是否能帮忙编译加入？v3版本最棒的地方就在于能够自动获取IP。在winserver上使用不同端口能让v2v3俩一起工作，不知道openwrt的行不行。

**Comment by DHDAXCW** [comment]
有源吗？

**Comment by cnJJHC** [comment]
不好意思回复的晚了：
N2N的Github地址https://github.com/ntop/n2n。
前面说错了，自动获取IP的功能之前v2也能用或配合DHCP服务器，就是成功率低。直到v3才稳定起来，所以自动获取IP不是v3的新功能。
后来我看到大佬你的包内已经有N2N_v3.0，但是没有GUI界面管理起来有点不方便。（而且我也不清楚两个是否能同时开启使用，是不是要建立一个网口，还在摸索中……）

*题外：其中winserver上我直接下载这位博主（https://bugxia.com）的EasyN2N的/n2n_client文件夹里面做好的v2、v3版本的edge.exe和supernode.exe。在不同端口下实现的同一台主机架设两个版本的N2N服务端。

**Comment by DHDAXCW** [comment]
![image](https://user-images.githubusercontent.com/74764072/163714691-7ac046e0-e83c-49c1-916e-314e6fc67c61.png)

**Comment by cnJJHC** [comment]
论句号（。）的不必要性
N2N的Github地址[https://github.com/ntop/n2n]
