### ISSUE TITLE
请教各位大佬，有无可能解决docker+udp无法共存的问题

### ISSUE THREAD

**Issue by Raremaa** [DHDAXCW/NanoPi-R4S-R4SE#213]

**Comment by xspeed1989** [comment]
https://www.115115.xyz/everything/openwrt-udp-%E4%BB%A3%E7%90%86%E5%A4%B1%E6%95%88/
试试看

**Comment by xspeed1989** [comment]
> https://www.115115.xyz/everything/openwrt-udp-%E4%BB%A3%E7%90%86%E5%A4%B1%E6%95%88/ 试试看

@Raremaa https://github.com/DHDAXCW/NanoPi-R4S/releases/tag/2022.04.23-Lean5用这个加上面的配置，亲测可用

**Comment by Raremaa** [comment]
这个会带来其他奇奇怪怪问题吗

**Comment by xspeed1989** [comment]
目前没发现啥问题，用乞丐版吧

Raremaa ***@***.***> 于2022年4月24日周日 11:20写道：

**Comment by xspeed1989** [comment]
@Raremaa 好吧 我用的是友善的ROM 带Docker +上面的选项就可以转发UDP
