### ISSUE TITLE
无线连接卡死

### ISSUE THREAD

**Issue by LYK1013** [DHDAXCW/NanoPi-R4S-R4SE#219]
![微信图片_20220506190901](https://user-images.githubusercontent.com/44458329/167120589-65efe11b-067d-41fe-8b55-040ff8dfcdd4.png)

**Comment by LYK1013** [comment]
CF-822AC

**Comment by DHDAXCW** [comment]
5.15内核对无线没办法整了。。。只能刷5.4内核
