### ISSUE TITLE
稳定版 ap漫游延迟高 正式版正常

### ISSUE THREAD

**Issue by dysysqf** [DHDAXCW/NanoPi-R4S-R4SE#222]
稳定版 ap漫游延迟高 正式版正常

**Comment by dysysqf** [comment]
这几天刷了别的几个固件，包括小朋友的固件都一样 除了友善官方的AP漫游很稳定 基本上延迟都很高 数据卡顿严重

**Comment by mimosa** [comment]
> 这几天刷了别的几个固件，包括小朋友的固件都一样 除了友善官方的AP漫游很稳定 基本上延迟都很高 数据卡顿严重

怎么复现这个问题呢？

**Comment by dysysqf** [comment]
我的环境是 网件rax80 + 网件eax80
________________________________
