### ISSUE TITLE
本地编译指导

### ISSUE THREAD

**Issue by Jona-lee** [DHDAXCW/NanoPi-R4S-R4SE#223]
求指导，如何基于你的版本，pull我本机修改编译，想修改一些内核的配置

**Comment by DHDAXCW** [comment]
我改的是为了本地托管用的，你想要用的话可以直接 https://github.com/DHDAXCW/NanoPi-R4S/tree/94dd3c4ca5d0c73a776a9c6e688d5a2812a0cbd3   这个版本是GitHub actions编译的
