### ISSUE TITLE
超频版的稳定性咋样？

### ISSUE THREAD

**Issue by solaris111** [DHDAXCW/NanoPi-R4S-R4SE#231]
请教下作者和各位玩友，超频版的稳定性如何？有没有长期重载出现死机的情况？我是想借鉴下这个超频的opp参数用在ubuntu上。@[DHDAXCW](https://github.com/DHDAXCW)
原厂给出的VDD参数是不是太保守了？
![rk3399-vdd](https://user-images.githubusercontent.com/69401444/171055878-391a585e-c764-4dad-ac94-6380eed78433.png)

**Comment by DHDAXCW** [comment]
这个芯片手册推荐供电是1.25v
![image](https://user-images.githubusercontent.com/74764072/171072029-13681d73-965d-4c33-8fdd-d84b4ae22a4d.png)

上游直接给大核心用1.32v供电了。。。
![image](https://user-images.githubusercontent.com/74764072/171072317-66da1010-067b-482f-bbfd-6fbe45ad49fe.png)

之前改过1.27v，就死机了。可能是体质问题吧
反正用1.32v没什么大不了

**Comment by solaris111** [comment]
我看到了，就是感觉电压超的略高。请教下您，有没有做过压力测试，做了多久？cpu温度能到多少？

**Comment by Robird** [comment]
别超，这两天江苏气温40度，几乎天天死机。我折腾改参数呢。
