### ISSUE TITLE
5.15_稳定版  eth1 从1000Mb/s降为100Mb/s

### ISSUE THREAD

**Issue by StephenLiz** [DHDAXCW/NanoPi-R4S-R4SE#232]
版本：2022.05.27 NanoPi-R4S-linux.5.15_稳定版_精简
 
状态 => 概览 => 接口

问题：eth1 仅为100Mb/s，不应该是1000Mb/s才对的吗？如何修改？
![图片 1](https://user-images.githubusercontent.com/51089333/171211992-441028f3-974f-4ba1-bf21-42c3eb8aff19.png)

**Comment by StephenLiz** [comment]
> 换5e以上的网线

用其他仓库的R4S，eth1都是1000Mb/s，可以排除网线问题，但他们都没骷髅头的稳定版的稳定。

**Comment by evenlinyf** [comment]
我的好像也是会降到100M， 重启光猫和路由器才行

**Comment by StephenLiz** [comment]
> 我的好像也是会降到100M， 重启光猫和路由器才行

我做了以下操作后，eth1 恢复为1000Mb/s
1.删除部分用不到的app后
2.CPU Freq 中 Policy0 及Policy 4设定为1416000
3.断电重启（非软重启）
![image](https://user-images.githubusercontent.com/51089333/173192961-40c6f2b4-0e74-4b07-ac57-81bc27281817.png)

![image](https://user-images.githubusercontent.com/51089333/173192667-a2ad5d0a-3b7f-4f2e-a4ca-ee3c4c9d8181.png)
具体是哪一个影响，有待测试

**Comment by foxparpar** [comment]
> CPU Freq 中 Policy0 及Policy 4设定为1416000

CPU按照这个参数设置重启后，eth1恢复正常，今早起来又掉到100m了，看来不是CPU插件的问题。

**Comment by ydnm** [comment]
> 

是光猫桥接模式 ？电信宽带？ 可能是电信对桥接的限制

**Comment by evenlinyf** [comment]
升级了6.15 正式版全插件用了几天， 我这里是已经不会降带宽了

**Comment by Ymy0825** [comment]
终于不会降带宽了，我现在马上刷上测试

**Comment by Xlyaon** [comment]
换tf卡，玄学问题基本都跟tf卡有点关系，最好是slc mlc工业卡，或者mlc监控卡也行，最低就是老款mlc普通卡
