### ISSUE TITLE
更改lan地址后，后台无法访问

### ISSUE THREAD

**Issue by Zayia** [DHDAXCW/NanoPi-R4S-R4SE#234]
提示luci不存在

**Comment by KenshinLam** [comment]
我也遇到异样的问题，请问怎么解决

**Comment by KuCoXi** [comment]
我是改了lan口IP就没有DHCP，必须手动改电脑IP和网关才能打开后台，改回默认的192.168.11.1又可以了，不知道啥问题

**Comment by SiMplTon-B** [comment]
说句难听的 傻瓜式合适你们用 (滑稽)
