### ISSUE TITLE
R4S版和R4SE两种固件的区别在什么地方？

### ISSUE THREAD

**Issue by Xlyaon** [DHDAXCW/NanoPi-R4S-R4SE#245]

**Comment by DHDAXCW** [comment]
多了emmc  ![image](https://user-images.githubusercontent.com/74764072/178712057-a55644be-dced-4554-97b4-6b085c017766.png)

**Comment by Xlyaon** [comment]
> 多了emmc ![image](https://user-images.githubusercontent.com/74764072/178712057-a55644be-dced-4554-97b4-6b085c017766.png)

谢谢解答

**Comment by gngpp** [comment]
请问，r4se，从SD卡启动刷哪个版本固件，emmc 引导已经擦除了，发现刷了两个版本都无法从tf启动，系统灯不亮。是只支持emmc固件吗？

**Comment by DHDAXCW** [comment]
> 请问，r4se，从SD卡启动刷哪个版本固件，emmc 引导已经擦除了，发现刷了两个版本都无法从SD卡启动，系统灯不亮。是只支持emmc固件吗？

emmc清空了吗？
