### ISSUE TITLE
您所有的新固件都无法启动

### ISSUE THREAD

**Issue by Wangshengli05** [DHDAXCW/NanoPi-R4S-R4SE#246]
您所有的新固件都无法启动..您自己测试了吗？他们都未能启动。只有 7 月 4 日的固件还可以。 7 月 4 日之后，所有固件都无法启动

**Comment by DHDAXCW** [comment]
是7.17吗?

**Comment by DHDAXCW** [comment]
都能启动呢、、、
![image](https://user-images.githubusercontent.com/74764072/179381417-0612480e-4382-43d1-aabb-8f5a01a5902d.png)
![image](https://user-images.githubusercontent.com/74764072/179381472-ddc4912c-a72f-4cf8-b674-cf31c510b0d3.png)

**Comment by Wangshengli05** [comment]
7 月 13 日、14 日、16 日、17 日。 所有 R4S 启动失败。 你可以试试看。 只有7月4日是可以的
王胜利

Sent from Yahoo Mail on Android 
 
  On Sun, 17 Jul 2022 at 10:33 am, ***@***.***> wrote:   


都能启动呢、、、

**Comment by DHDAXCW** [comment]
也试了 14 16能启动

**Comment by Wangshengli05** [comment]
试试看。 都失败了。  7月17日也失败了。

Sent from Yahoo Mail on Android 
 
  On Sun, 17 Jul 2022 at 11:16 am, ***@***.***> wrote:   


也试了 14 16能启动

**Comment by Wangshengli05** [comment]
删除 7 月 17 日。 我尝试了所有，但都失败了

Sent from Yahoo Mail on Android 
 
  On Sun, 17 Jul 2022 at 12:18 pm, Quintus Yao ***@***.***> wrote:   试试看。 都失败了。  7月17日也失败了。

Sent from Yahoo Mail on Android 
 
  On Sun, 17 Jul 2022 at 11:16 am, ***@***.***> wrote:   


也试了 14 16能启动

**Comment by DHDAXCW** [comment]
换卡了？

**Comment by Fvpder** [comment]
试了一下7.17能正常启动，更换内存卡试试，长期使用建议更换mlc颗粒的内存卡

**Comment by Wangshengli05** [comment]
我现在不会买新的TF卡。  MLC 卡很慢。  Slc 单层卡速度很快。 我有很多卡我无法再次添加新卡

Sent from Yahoo Mail on Android 
 
  On Sun, 17 Jul 2022 at 3:45 pm, ***@***.***> wrote:   


试了一下7.17能正常启动，更换内存卡试试，长期使用建议更换mlc颗粒的内存卡

**Comment by Fvpder** [comment]
The translation is terrible, that I cannot unserstand you. I was wondering if you are using the r4se version, which is developed for a new type with emmc flash inside.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月17日(星期天) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DHDAXCW/NanoPi-R4S-R4SE] 您所有的新固件都无法启动 (Issue #246)





 我现在不会买新的TF卡。&nbsp; MLC 卡很慢。&nbsp; Slc 单层卡速度很快。 我有很多卡我无法再次添加新卡
 
 Sent from Yahoo Mail on Android 
  
   On Sun, 17 Jul 2022 at 3:45 pm, ***@***.***&gt; wrote:   
 
 
 试了一下7.17能正常启动，更换内存卡试试，长期使用建议更换mlc颗粒的内存卡

**Comment by Wangshengli05** [comment]
I use R4S.  I don't use r4se

Sent from Yahoo Mail on Android 
 
  On Sun, 17 Jul 2022 at 5:38 pm, ***@***.***> wrote:   

The translation is terrible, that I cannot unserstand you. I was wondering if you are using the r4se version, which is developed for a new type with emmc flash inside.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月17日(星期天) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DHDAXCW/NanoPi-R4S-R4SE] 您所有的新固件都无法启动 (Issue #246)





 我现在不会买新的TF卡。&nbsp; MLC 卡很慢。&nbsp; Slc 单层卡速度很快。 我有很多卡我无法再次添加新卡
 
 Sent from Yahoo Mail on Android 
 
 On Sun, 17 Jul 2022 at 3:45 pm, ***@***.***&gt; wrote: 
 
 
 试了一下7.17能正常启动，更换内存卡试试，长期使用建议更换mlc颗粒的内存卡

**Comment by Wangshengli05** [comment]
换什么卡？ 我有 4 张抽认卡，我都炸了，但没有用。 固件有问题

Sent from Yahoo Mail on Android 
 
  On Sun, 17 Jul 2022 at 12:46 pm, ***@***.***> wrote:   


换卡了？
