### ISSUE TITLE
fusionwrt r4s  断电恢复供电后无法进入系统

### ISSUE THREAD

**Issue by mrkinow** [DHDAXCW/NanoPi-R4S-R4SE#248]
如题，停电后接通r4s电源，仍然无法进入后台，且无法联网，只能多次按reset键才行

**Comment by DHDAXCW** [comment]
什么版本？

**Comment by mrkinow** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DHDAXCW/NanoPi-R4S-R4SE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月18日(星期一) 中午11:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DHDAXCW/NanoPi-R4S-R4SE] fusionwrt r4s  断电恢复供电后无法进入系统 (Issue #248)





 
什么版本？

**Comment by DHDAXCW** [comment]
刷最新固件sq格式
