### ISSUE TITLE
硬盘休眠后无法唤醒

### ISSUE THREAD

**Issue by xiaojun-space** [DHDAXCW/NanoPi-R4S-R4SE#250]
在“网络储存”中设置了“硬盘休眠”，第二天无法唤醒硬盘。
使用的是R4s 7.17最新的包

系统日志如下：
![IMG_3990](https://user-images.githubusercontent.com/93051683/179883626-454bcc0a-4257-4985-8678-a2f53f84b8dc.jpeg)

**Comment by DHDAXCW** [comment]
已处理 刷最新即可
