### ISSUE TITLE
2022.07.21 NanoPi-R4S-linux-5.15_正式版_全插件 不能安装iptables-mod-nat-extra

### ISSUE THREAD

**Issue by skywing918** [DHDAXCW/NanoPi-R4S-R4SE#252]
$ opkg install iptables-mod-nat-extra
Unknown package 'iptables-mod-nat-extra'.
Collected errors:
 * opkg_install_cmd: Cannot install package iptables-mod-nat-extra.

iKoolProxy 还是没有

**Comment by xuanranran** [comment]
先运行opkg update

**Comment by DHDAXCW** [comment]
下版本加上去

**Comment by DHDAXCW** [comment]
刷最新即可
