### ISSUE TITLE
package-server.zip 是怎么生成的，没找到是哪个选项开启

### ISSUE THREAD

**Issue by zhangguanzhang** [DHDAXCW/NanoPi-R4S-R4SE#255]
我看了github action的yml步骤里有删掉生成的 package-server.zip 文件

**Comment by DHDAXCW** [comment]
对啊 删了，省流量呗，节约~

**Comment by DHDAXCW** [comment]
https://github.com/DHDAXCW/NanoPi-R4S-R4SE/blob/main/.github/workflows/NanoPi-R4S-Lite.yml#L97

**Comment by zhangguanzhang** [comment]
就是package 目录打包吗

**Comment by DHDAXCW** [comment]
在这里路径/bin/packages文件夹里就是

**Comment by zhangguanzhang** [comment]
好的
