### ISSUE TITLE
7月23日正式版R4S经常过几天忽然上不了网

### ISSUE THREAD

**Issue by kokpk** [DHDAXCW/NanoPi-R4S-R4SE#261]
刚入手R4S 4G企业版刷的7.23正式版但经常有过了几天上不了网，其中一次抓到日志显示kern.err kernel: [486478.783931] rcu: INFO: rcu_preempt self-detected stall on CPU。进入openwrt接口和状态都进不去。最后只能拔电源重启解决。请问这是超频原因吗？还是硬件本身的问题。

**Comment by DHDAXCW** [comment]
电源自己解决

**Comment by kokpk** [comment]
已经是5V3A的了。。有推荐的电源吗。。
