### ISSUE TITLE
当passwall中模式选择为“中国列表之外”时， 安卓手机就连接不上softether VPN

### ISSUE THREAD

**Issue by wslftx** [DHDAXCW/NanoPi-R4S-R4SE#262]
骷髅头大神，

我一直在使用你的DHDAXCW @ FusionWrt 20211110 R21.11.11 (2021-11-10) / LuCI Master (git-21.280.14233-9b796b1)这个版本的固件，最近发现当passwall中模式选择为“中国列表之外”时， 安卓手机就连接不上softether VPN，选择“GFW列表”时就可以，请问要如何解决？
（注：因为最近发现只用GFW列表时，有些网址显示不完整，切换到“中国列表之外”时就发现原来手机连接不上softether VPN了。这些列表有设置陈每晚自动更新的）。

感谢大神的付出，期待大神的回复。

致以诚挚的问候，

墙内一小民

**Comment by DHDAXCW** [comment]
这有点老  刷最新吧
