### ISSUE TITLE
请帮忙看下 R4s间歇断网问题

### ISSUE THREAD

**Issue by MethodJiao** [DHDAXCW/NanoPi-R4S-R4SE#265]
我的r4s刷了您的固件，但是只要打开passwall就会有时候间歇断网

![image](https://user-images.githubusercontent.com/45934872/188547490-613e2408-569b-4389-b12d-3df0dac2a059.png)

（我写了个程序定位了11点40分和12点19分断网，日志截图是我在12点19分截取的）

内核日志和系统日志附上如下

![image](https://user-images.githubusercontent.com/45934872/188547361-80b9d44b-b979-4101-9439-3cef21f5cc1a.png)
![image](https://user-images.githubusercontent.com/45934872/188547389-57dc09e6-a783-4f3d-b90c-343173aa6f89.png)

**Comment by MethodJiao** [comment]
不知道是否是passwall插件和系统产生了什么样的反应，我也有试过openclash，情况依旧

**Comment by MethodJiao** [comment]
![image](https://user-images.githubusercontent.com/45934872/188547754-c6c0aa30-925c-49ac-acd9-86fd9933aaf1.png)
系统版本供大神定位

**Comment by DHDAXCW** [comment]
刷最新吧

**Comment by DHDAXCW** [comment]
如果你一直跑下载，那他就炸了，。

**Comment by MethodJiao** [comment]
> 如果你一直跑下载，那他就炸了，。

刷了最新目前还没问题，很神奇
