### ISSUE TITLE
DNS 问题

### ISSUE THREAD

**Issue by happyaguang** [DHDAXCW/NanoPi-R4S-R4SE#270]
hello world 开全局，访问whoer.net，ip成功出国，dns没出国，怎么配置能让dns 出国？
试过改WAN口，LAN口，都没用。改本地网络连接的DNS也没用。
刷新whoer页面，DNS偶尔会变成美国，再刷新又变回中国。

如果使用本地客户端 QV2RAY、小火箭，再访问 whoer，就没这问题

![微信截图_20220922153109](https://user-images.githubusercontent.com/18143940/191685957-8ccaa922-70f9-49b7-9398-a0ce50d61c3c.png)

**Comment by DHDAXCW** [comment]
![image](https://user-images.githubusercontent.com/74764072/192107819-f46d5396-809c-423f-88e4-775e1fce0365.png)
**擦掉即可**

**Comment by happyaguang** [comment]
> Owner

大神你好，问题还是依旧。我刷的全新系统，没做任何设置，只设置了hello world。
按照您的方法，把防火墙规则都删掉了，问题依旧，whoer 里的dns 还是显示中国。
