### ISSUE TITLE
SFE 导致流量监测功能失效

### ISSUE THREAD

**Issue by greenhat616** [DHDAXCW/NanoPi-R4S-R4SE#271]
RT，默认在 Turbo ACC 里面开启的 SFE（Shortcut-FE）功能会导致流量监测功能（具体到单个 IP 的）失效，据说也可能导致协议嗅探失效？（这个我不尝试过）

高格固件宣传解决了个这个问题，也许我们可以尝试使用高格的方法解决这个问题？

如果没办法兼容的话，建议大佬在 Readme 加一个提示，如果有需要这一系列功能的话，手动关闭 SFE 功能.

**Comment by DHDAXCW** [comment]
我这个要在下版本取消sfe了
