### ISSUE TITLE
最新版取消了smartdns的问题

### ISSUE THREAD

**Issue by alvisxinbin** [DHDAXCW/NanoPi-R4S-R4SE#272]
大神你好，我是你的忠实粉丝。
无论我什么时候尝试刷其他固件，都不能让我满意，唯有骷髅头是最终的归宿！
但是最近最新固件中少了我最爱的smartdns 这个插件，请问可否在后续版本中增加这个插件。
膜拜！感谢🙏

使用设备：R4S 和 R2S

**Comment by DHDAXCW** [comment]
......下版本吧。。

**Comment by alvisxinbin** [comment]
非常感谢！

骷髅头 ***@***.***> 於 2022年10月5日 週三 15:16 寫道：
