### ISSUE TITLE
最新的10.16版本ADguardHome有点问题

### ISSUE THREAD

**Issue by flyingcrylife** [DHDAXCW/NanoPi-R4S-R4SE#283]
执行文件路径/usr/bin/AdGuardHome会提示报错找不到路径，改成/usr/bin/AdGuardHome/AdGuardHome就好了，然后问一下大佬，怎么argon主题的设置页面怎么没有了，是去掉了吗？

**Comment by DHDAXCW** [comment]
感谢反馈，但是这个并不是正式发布的版本，我需要更多测试和反馈，改进编译缺少什么东西。
这个AdGuardHome需要自己动手改路径，我也没没撤了。。。
收到很多人反馈是argon主题，我也发现到丢了下载链接，现在已加上了，明天10.17版就有了。
