### ISSUE TITLE
10.17版本的SR+和helloworld有问题

### ISSUE THREAD

**Issue by happyaguang** [DHDAXCW/NanoPi-R4S-R4SE#284]
配置了trojan 绕过大路IP模式，极不稳定。
要不就是自动变成会全局上网，要不就是断网连不上（节点确定没问题）

**Comment by DHDAXCW** [comment]
我改的有问题，等今天版本吧

**Comment by happyaguang** [comment]
> 我改的有问题，等今天版本吧

全新重刷的19号的版本，helloworld还是有问题。配置好了后国内国外都访问不了了，就是断网了 ，而且我并没有设置全局。

**Comment by DHDAXCW** [comment]
https://github.com/DHDAXCW/NanoPi-R4S-R4SE/releases/tag/2022.10.20-Lean3

**Comment by DHDAXCW** [comment]
已解决 刷最新即可
