### ISSUE TITLE
ac1200网卡  rtl8812 新固件无法识别

### ISSUE THREAD

**Issue by Horus-K** [DHDAXCW/NanoPi-R4S-R4SE#299]
https://github.com/DHDAXCW/NanoPi-R4S-R4SE/issues/4
大佬可以帮看看么，之前固件可以用的，最新的固件没法识别了，直接创建/etc/config/wireless也无法使用网卡

**Comment by Horus-K** [comment]
![image](https://user-images.githubusercontent.com/48319268/211747839-6da57ddc-5e2b-4d45-8405-c4943ba1eafd.png)

我找到的这些包最低内核要求5.4.225  我下载最新固件的内核是5.4.118
https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/targets/rockchip/armv8/
大佬有合适的包地址吗

**Comment by DHDAXCW** [comment]
在路由器上,系统--软件包--刷新--搜搜驱动--安装

**Comment by stronger2021** [comment]
确实。我也发现用不了。😭

**Comment by Horus-K** [comment]
应该是仓库版本太低了，21版本有对应的驱动http://mirrors.cloud.tencent.com/openwrt/releases/21.02.5/targets/rockchip/armv8/packages/
看来要到官网看看咋编译了😂😂
