### ISSUE TITLE
PCHiFi 数字转盘遥控启动不了

### ISSUE THREAD

**Issue by liuquanqing** [DHDAXCW/NanoPi-R4S-R4SE#305]
如题

**Comment by gngpp** [comment]
> 如题

![image](https://user-images.githubusercontent.com/51810656/213862434-0ff4e7b4-db2d-41a4-81bd-db1766db8628.png)

**Comment by liuquanqing** [comment]
启动几秒钟后就停止运行了，R4S ，网上搜了不止一个人有这个问题（其他固件也有）

**Comment by liuquanqing** [comment]
搞不懂，日志也没有(cat /var/log/forked-daapd.log)，  
放弃了,其实就想简单弄个QPlay推送的播放器，之前有一个支持的软件忘了叫啥了，airplay2是可以用的

**Comment by liuquanqing** [comment]
换了Docker版本的就好了，full的打不开
