### ISSUE TITLE
可以把R4S显卡驱动编译到docker的固件里面吗

### ISSUE THREAD

**Issue by hupimaodaren007** [DHDAXCW/NanoPi-R4S-R4SE#321]
可以把R4S显卡驱动编译到docker的固件里面吗

**Comment by GreenTeodoro839** [comment]
之前有，但是不知道什么原因现在带上就编译失败

**Comment by hupimaodaren007** [comment]
现在不能编译了吗，那就没法用jellfin，我下载源码编译的时候报错。

**Comment by hupimaodaren007** [comment]
之前的是哪个版本带啊，内核版本是多少

**Comment by GreenTeodoro839** [comment]
> 现在不能编译了吗，那就没法用jellfin，我下载源码编译的时候报错。

不知道哪里出了问题，好像是去年年底上游改了什么东西
