### ISSUE TITLE
r4s docker版固件会自动重置重启

### ISSUE THREAD

**Issue by s949492225** [DHDAXCW/NanoPi-R4S-R4SE#327]
r4s docker版固件会自动重置重启
导致配置丢失

docker的存储路径已经改为移动硬盘
docker内跑了jellyfin

版本号: OpenWrt Rockchip / LuCI Master (git-23.167.03555-4ac4bf5)

**Comment by s949492225** [comment]
docker不跑容器，就不会出现自动重置现象，
是否和移动硬盘有关系？或者是其他原因

**Comment by SuChenawa** [comment]
我也遇到了相同的问题，路由器内软重启不会出问题，但是使用路由器内的定时重启或者手动断电重启就会出现配置丢失的问题
但是不同的是，我不开docker也会触发

**Comment by DHDAXCW** [comment]
刷的是最新吗？帮忙测试下最新

**Comment by SuChenawa** [comment]
抱歉，我目前使用的是4月份的一个稳定固件，所以暂时没有办法进行测试

骷髅头 ***@***.***> 于 2023年7月18日周二 08:30写道：
